apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt
  namespace: gateway-demo
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: 'paolos0@microsoft.com'
    privateKeySecretRef:
      name: letsencrypt
    solvers:
      - http01:
          gatewayHTTPRoute:
            parentRefs:
              - name: httpbin-gateway
                namespace: gateway-demo
                kind: Gateway